spring:
  application:
    name: edu.jorge.proyectodaw
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu.jorge.proyectodaw?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  sql:
    init:
      mode: always
      platform: mysql
      data-locations: classpath:db/initialData.sql
  output:
    ansi:
      enabled: always
server:
  port: 8080